config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  get 'users/create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  root "sessions#new"
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts, only: [:new, :create, :index]
  resources :users, only: [:new, :create, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  before_create :assign_token
  has_secure_password
  has_many :posts
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :name, presence: true, length: { minimum: 4, maximum: 50 }
  validates :email, presence: true, uniqueness: true, length: { maximum: 50 },
                    format: { with: EMAIL_REGEX }
  validates :password, presence: true, length: { minimum: 6, maximum: 20 }

  def assign_token
    self.remember_digest = User.encrypt(User.new_token)
  end

  class << self
    # Returns a random token.
    def new_token
      SecureRandom.urlsafe_base64
    end

    # Returns an encrypted version of the string passed.
    def encrypt(string)
      Digest::SHA1.hexdigest(string)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def log_in(user)
    session[:user_id] = user.id
    user.assign_token
    user.update(remember_digest: user.remember_digest)
    cookies.permanent.encrypted[:user_id] = user.id
    cookies.permanent[:remember_digest] = user.remember_digest
    define_user(user)
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def define_user(user)
    @current_user = user
  end

  def log_out
    session.delete(:user_id)
    cookies.delete(:user_id)
    cookies.delete(:remember_digest)
    define_user(nil)
  end

  def logged_user?
    redirect_to root_url if session[:user_id].nil?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_user?, only: %i[new create]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.save
    redirect_to '/posts'
  end

  def index
    @posts = Post.all
    authors_ids = @posts.map(&:user_id)
    @authors_names = authors_ids.map { |author_id| User.find(author_id).name }
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user&.authenticate(params[:session][:password])
      log_in(@user)
      redirect_to posts_path
    else
      render '/sessions/new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'Account created successfully'
      log_in(@user)
      redirect_to posts_url
    else
      render 'users/new'
    end
  end

  def index
    @user = User.new
    render 'users/new'
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |message| %>
      <%= message %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>All posts</h1>

<% if cookies[:user_id] %>
  <%= link_to 'Create a new post!', new_post_path %>
  <span>&nbsp;&nbsp;</span>
  <%= link_to 'Logout', logout_path, method: :delete%>
<% else %>
  <%= link_to 'Log in!', root_path %>
  <span>&nbsp;</span>
  <span>&nbsp;</span>
  <%= link_to 'Sign up!', signup_path %>
<% end %>

<ol>
  <% @posts.each_with_index do |post, index| %>
    <li>Title: <%= post.title %><br><br>
      Body: <%= post.body %>
    </li>
    <% if cookies[:user_id] %>
      <p>Authors: <%= @authors_names[index] %></p>
    <% end %>
    <br><br>
  <% end %>
</ol>

app/views/posts/new.html.erb
<h1>Create a post</h1>

<%= form_with(model: @post, local: true) do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title, size: 50 %><br><br>

  <%= f.label :body %><br>
  <%= f.text_area :body, cols: 50, rows: 10 %><br><br>

  <%= f.submit 'Create' %>
<% end %>
<br>
<%= link_to '<< Go back', posts_path %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<%= @user.errors.full_messages unless @user.errors.empty? %>
<h1>Sign Up</h1>

<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name, size: 50 %><br><br>

  <%= f.label :email %><br>
  <%= f.email_field :email, size: 50 %><br><br>

  <%= f.label :password %><br>
  <%= f.password_field :password, size: 50 %><br><br>

  <%= f.label :password_confirmation %><br>
  <%= f.password_field :password_confirmation, size: 50 %><br><br>

  <%= f.submit 'Create your account' %>
<% end %>

<br>

<%= link_to 'Home', root_path %>